2023-04-03 18:49:31 kafka.conn   INFO     <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2023-04-03 18:49:31 kafka.conn   INFO     Probing node bootstrap-0 broker version
2023-04-03 18:49:33 root         ERROR    Unable to connect to Kafka listener
2023-04-03 18:49:33 root         ERROR    NoBrokersAvailable
Traceback (most recent call last):
  File "C:\Work\GitHub\DataEngineerLearningPath\Docker\Challenge 2\python script\utils\Kafka.py", line 21, in connectKafka
    kafka_consumer = KafkaConsumer(
  File "C:\Users\mherr\AppData\Local\Programs\Python\Python39\lib\site-packages\kafka\consumer\group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "C:\Users\mherr\AppData\Local\Programs\Python\Python39\lib\site-packages\kafka\client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "C:\Users\mherr\AppData\Local\Programs\Python\Python39\lib\site-packages\kafka\client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
